# Generated by Django 5.2.5 on 2025-08-24 09:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_address',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events',
            field=wagtail.fields.StreamField([('event', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.DateBlock', (), {}), 2: ('wagtail.blocks.TimeBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('time', 2), ('description', 3)]], {})}, help_text='Upcoming events'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_images',
            field=wagtail.fields.StreamField([('gallery_item', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {})}, help_text='Parish gallery images'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='A Community of Faith and Love', help_text='Subtitle for the hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Our Lady of Fatima Church', help_text='Main title for the hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Welcome message content'),
        ),
    ]
